services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile    # 映射Caddyfile配置
      - ./html:/var/www/html                # 映射web内容
    restart: always
